// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Dashboard_page_ from "./routes/Dashboard/[page].tsx";
import * as $Dashboard_raffle_New from "./routes/Dashboard/raffle/New.tsx";
import * as $Dashboard_raffle_raffleId_ from "./routes/Dashboard/raffle/[raffleId].tsx";
import * as $Raffles from "./routes/Raffles.tsx";
import * as $SuccessfulPucharse_ticketId_ from "./routes/SuccessfulPucharse/[ticketId].tsx";
import * as $Support from "./routes/Support.tsx";
import * as $Verify from "./routes/Verify.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_buyRandomTicket from "./routes/api/buyRandomTicket.ts";
import * as $api_buySelectedTickets from "./routes/api/buySelectedTickets.ts";
import * as $api_confirmPayment from "./routes/api/confirmPayment.ts";
import * as $api_getPendingPaymentsList from "./routes/api/getPendingPaymentsList.ts";
import * as $api_getRejectedPaymentsList from "./routes/api/getRejectedPaymentsList.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_newRaffle from "./routes/api/newRaffle.ts";
import * as $api_rejectPayment from "./routes/api/rejectPayment.ts";
import * as $api_verifyTicket from "./routes/api/verifyTicket.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $raffle_raffleId_ from "./routes/raffle/[raffleId].tsx";
import * as $Buyer from "./islands/Buyer.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import * as $NewRaffle from "./islands/NewRaffle.tsx";
import * as $PendingPaymentsList from "./islands/PendingPaymentsList.tsx";
import * as $RandomTickets from "./islands/RandomTickets.tsx";
import * as $TicketsSelector from "./islands/TicketsSelector.tsx";
import * as $UserAgreementsModal from "./islands/UserAgreementsModal.tsx";
import * as $Verifier from "./islands/Verifier.tsx";
import * as $login_1 from "./islands/login.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Dashboard/[page].tsx": $Dashboard_page_,
    "./routes/Dashboard/raffle/New.tsx": $Dashboard_raffle_New,
    "./routes/Dashboard/raffle/[raffleId].tsx": $Dashboard_raffle_raffleId_,
    "./routes/Raffles.tsx": $Raffles,
    "./routes/SuccessfulPucharse/[ticketId].tsx": $SuccessfulPucharse_ticketId_,
    "./routes/Support.tsx": $Support,
    "./routes/Verify.tsx": $Verify,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/buyRandomTicket.ts": $api_buyRandomTicket,
    "./routes/api/buySelectedTickets.ts": $api_buySelectedTickets,
    "./routes/api/confirmPayment.ts": $api_confirmPayment,
    "./routes/api/getPendingPaymentsList.ts": $api_getPendingPaymentsList,
    "./routes/api/getRejectedPaymentsList.ts": $api_getRejectedPaymentsList,
    "./routes/api/login.ts": $api_login,
    "./routes/api/newRaffle.ts": $api_newRaffle,
    "./routes/api/rejectPayment.ts": $api_rejectPayment,
    "./routes/api/verifyTicket.ts": $api_verifyTicket,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/raffle/[raffleId].tsx": $raffle_raffleId_,
  },
  islands: {
    "./islands/Buyer.tsx": $Buyer,
    "./islands/NavBar.tsx": $NavBar,
    "./islands/NewRaffle.tsx": $NewRaffle,
    "./islands/PendingPaymentsList.tsx": $PendingPaymentsList,
    "./islands/RandomTickets.tsx": $RandomTickets,
    "./islands/TicketsSelector.tsx": $TicketsSelector,
    "./islands/UserAgreementsModal.tsx": $UserAgreementsModal,
    "./islands/Verifier.tsx": $Verifier,
    "./islands/login.tsx": $login_1,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
