// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Accounts from "./routes/Accounts.tsx";
import * as $Raffles from "./routes/Raffles.tsx";
import * as $Verify from "./routes/Verify.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $index from "./routes/index.tsx";
import * as $raffle_raffleId_ from "./routes/raffle/[raffleId].tsx";
import * as $Buyer from "./islands/Buyer.tsx";
import * as $NavBar from "./islands/NavBar.tsx";
import * as $UserAgreementsModal from "./islands/UserAgreementsModal.tsx";
import * as $Verifier from "./islands/Verifier.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Accounts.tsx": $Accounts,
    "./routes/Raffles.tsx": $Raffles,
    "./routes/Verify.tsx": $Verify,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/index.tsx": $index,
    "./routes/raffle/[raffleId].tsx": $raffle_raffleId_,
  },
  islands: {
    "./islands/Buyer.tsx": $Buyer,
    "./islands/NavBar.tsx": $NavBar,
    "./islands/UserAgreementsModal.tsx": $UserAgreementsModal,
    "./islands/Verifier.tsx": $Verifier,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
